//引入express模块
const express=require("express");
//定义路由级中间件
const router=express.Router();

router.get("/SecondaryPageRouterData",(req,res)=>{
  var SecondaryPageRouterData=[
    {
        firstGroup:[
            {
                pageName:'数据接入情况',
                pagePath:'DataAccessSituation'
            },
            {
                pageName:'数据特征库',
                pagePath:'DataFeatureLibrary'
            },
            {
                pageName:'数据处理记录',
                pagePath:'DataFeatureLibrary'
            }
        ]
    },
    {
        secondGroup:[
            {
                pageName:'融合数据查询',
                pagePath:'search'
            },
            {
                pageName:'实名制数据查询',
                pagePath:'RealNameDataQuery'
            },
            {
                pageName:'实名制数据查询',
                pagePath:'RealNameDataQuery'
            },
            {
                pageName:'重点人员库',
                pagePath:'KeyStaffBank'
            },
            {
                pageName:'售处信息维护',
                pagePath:'SaleInfoMaintenance'
            },
            {
                pageName:'窗口信息维护',
                pagePath:'WindowInfoMaintenance'
            },
            {
                pageName:'全国站点信息',
                pagePath:'NationalSiteInformation'
            },
            {
                pageName:'查询结果',
                pagePath:'NationalSiteInformation'
            },
            {
                pageName:'上传',
                pagePath:'NationalSiteInformation'
            }
        ]
    },
    {
        thirdGroup:[
            {
                pageName:'综合研判',
                pagePath:'ComprehensiveStudy'
            },
            {
                pageName:'单目标分析',
                pagePath:'SingleObjectiveAnalysis'
            },
            {
                pageName:'多目标分析',
                pagePath:'MultiobjectiveAnalysis'
            },
            {
                pageName:'涉嫖建模分析',
                pagePath:'WhoringModelingAnalysis'
            },
            {
                pageName:'涉毒建模分析',
                pagePath:'DrugModelingAnalysis'
            },
            {
                pageName:'涉恐建模分析',
                pagePath:'TerrorModelingAnalysis'
            },
            {
                pageName:'侵财建模分析',
                pagePath:'InvadeMoneyModelingAnalysis'
            },
            {
                pageName:'维稳建模分析',
                pagePath:'MainStabilityModelingAnalysis'
            },
            {
                pageName:'中间库',
                pagePath:'IntermediateLibrary'
            },
            {
                pageName:'任务列表',
                pagePath:'TaskList'
            }
        ]
    },
    {
        fourthGroup:[
            {
                pageName:'综合预警',
                pagePath:'ComprehensiveEarlyWarning'
            },
            {
                pageName:'预警告警推送',
                pagePath:'WarningPush'
            }
        ]
    },
    {
        fifthGroup:[
            {
                pageName:'模型参数设置',
                pagePath:'ModelParameterSetting'
            },
            {
                pageName:'账号管理',
                pagePath:'AccountManagement'
            },
            {
                pageName:'部门管理',
                pagePath:'DepartmentManagement'
            },
            {
                pageName:'权限管理',
                pagePath:'AuthirityManagement'
            },
            {
                pageName:'权限管理',
                pagePath:'AuthirityManagement'
            },
            {
                pageName:'数据字典',
                pagePath:'DataDictionary'
            },
            {
                pageName:'系统配置',
                pagePath:'SystemConfiguration'
            },
            {
                pageName:'案件管理',
                pagePath:'CaseManagement'
            },
            {
                pageName:'执法日志',
                pagePath:'LawEnforcementLog'
            },
            {
                pageName:'接口推送',
                pagePath:'InterfacePush'
            },
            {
                pageName:'集群运行',
                pagePath:'ClusterOperation'
            }
        ]
    }
];
  res.json(SecondaryPageRouterData);
});

module.exports=router;