//引入express模块
const express=require("express");
//定义路由级中间件
const router=express.Router();

router.get("/indexNavData",(req,res)=>{
  var indexNavData=
    [
        {
            "firstLevelNav":"系统管理",
            "icon":"icon-yibiaopan",
            "show":false
        },
        {
            "firstLevelNav":"产品管理",
            "icon":"icon-desktop",
            "twoLevelNav":[
                            {
                                "pageName":"产品类表",
                                "url":"producttable"
                            },
                            {
                                "pageName":"品牌管理",
                                "url":"brand"
                            },
                            {
                                "pageName":"分类管理",
                                "url":"product"
                            }
            ],
            "show":false
        },
        {
            "firstLevelNav":"图片管理",
            "icon":"icon-picture",
            "twoLevelNav":[
                            {
                                "pageName":"广告管理",
                                "url":"adsmanagement"
                            },
                            {
                                "pageName":"分类管理",
                                "url":"PictureCat"
                            }
            ],
            "show":false
        },
        {
            "firstLevelNav":"交易管理",
            "icon":"icon-list1",
            "twoLevelNav":[
                            {
                                "pageName":"交易信息",
                                "url":"dealinformation"
                            },
                            {
                                "pageName":"交易订单(图)",
                                "url":"DealOrder"
                            },
                            {
                              "pageName":"订单管理",
                              "url":"OrderManagement"
                            },
                            {
                                "pageName":"交易金额",
                                "url":"DealFigure"
                            },
                            {
                                "pageName":"订单处理",
                                "url":"OrderOperate"
                            },
                            {
                                "pageName":"支付管理",
                                "url":"Paymanagement"
                            }
            ],
            "show":false
        },
        {
            "firstLevelNav":"会员管理",
            "icon":"icon-user",
            "twoLevelNav":[
                            {
                                "pageName":"会员列表",
                                "url":"MemberListpage"
                            },
                            {
                                "pageName":"等级管理",
                                "url":"LevelManagement"
                            },
                            {
                                "pageName":"会员记录管理",
                                "url":"MemberSecordManagement"
                            }
            ],
            "show":false
        },
        {
            "firstLevelNav":"消息管理",
            "icon":"icon-edit",
            "twoLevelNav":[
                            {
                                "pageName":"留言列表",
                                "url":"articlelist"
                            },
                            {
                                "pageName":"意见反馈",
                                "url":"classify"
                            }
            ],
            "show":false
        },
        {
            "firstLevelNav":"文章管理",
            "icon":"icon-edit",
            "twoLevelNav":[
                            {
                                "pageName":"文章列表",
                                "url":"articlelist"
                            },
                            {
                                "pageName":"分类",
                                "url":"classify"
                            }
            ],
            "show":false
        },
        {
            "firstLevelNav":"系统管理",
            "icon":"icon-cogs",
            "twoLevelNav":[
                            {
                                "pageName":"系统设置",
                                "url":"systemsetup"
                            },
                            {
                                "pageName":"栏目管理",
                                "url":"systemcolumnmanagement"
                            },
                            {
                                "pageName":"系统日志",
                                "url":"systemlog"
                            }
            ],
            "show":false
        },
        {
            "firstLevelNav":"管理员管理",
            "icon":"icon-group",
            "twoLevelNav":[
                            {
                                "pageName":"权限管理",
                                "url":"Administrator"
                            },
                            {
                                "pageName":"管理员列表",
                                "url":"Administratorlist"
                            },
                            {
                                "pageName":"个人信息",
                                "url":"Personal"}
            ],
            "show":false
        }
    ];
  res.json(indexNavData);
});

module.exports=router;